<!DOCTYPE html>
<html>
<head>

    @foreach($orders as $order)
    <title>J&T Waybill - Order #{{ $order->id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .waybill {
            width: 350px;
            border: 2px solid #000;
            padding: 15px;
            margin: 20px auto;
        }
        .section {
            border-bottom: 1px dashed #000;
            padding: 5px 0;
        }
        .section:last-child {
            border-bottom: none;
        }
        .section h4 {
            margin: 0 0 5px 0;
            font-size: 12px;
            text-transform: uppercase;
        }
        .section p {
            margin: 0;
            font-size: 12px;
        }
        .barcode {
            text-align: center;
            margin: 10px 0;
        }
        .barcode img {
            width: 80%;
            height: 50px;
        }
        .bold {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="waybill">
        <!-- Header -->
        <div class="section" style="text-align:center;">
            <h2>J&T Express</h2>
            <p class="bold">Waybill / Shipping Label</p>
        </div>

        <!-- Tracking number + barcode -->
        <div class="section barcode">
            <p class="bold">Tracking #: {{ $order->tracking_number }}</p>
            <!-- If you generate a barcode dynamically, insert here -->
            {{-- Example: <img src="data:image/png;base64,{{ $barcode }}" alt="barcode"> --}}
        </div>

        <!-- Sender Information -->
        <div class="section">
            <h4>Sender</h4>
            <p class="bold">{{ $order->sender_name ?? 'Salinio Drug Pharmacy' }}</p>
            <p>{{ $order->sender_address ?? 'Taguig C5' }}</p>
            <p>{{ $order->sender_phone ?? '09517372530' }}</p>
        </div>

        <!-- Recipient Information -->
        <div class="section">
            <h4>Recipient</h4>
            <p class="bold">{{ $order->customer->name }}</p>
            {{-- <p>{{ $order->shipping_address }}</p> --}}
            <p>{{ $order->phone ?? '' }}</p>
        </div>

        
        <!-- Package Details -->
        <div class="section">
            <h4>Package</h4>
            <p>Order ID: {{ $order->id }}</p>
            <p>Weight: {{ $order->weight ?? 'N/A' }} kg</p>
            <p>Service: {{ $order->service_type ?? 'Standard' }}</p>
        </div>

        <!-- Notes / COD / Payment -->
        <div class="section">
            <h4>Notes / COD</h4>
            <p>{{ $order->notes ?? 'None' }}</p>
        </div>


        @endforeach
        <!-- Footer -->
        <div class="section" style="text-align:center; font-size:10px;">
            <p>Generated by Your System</p>
            <p>Please handle with care</p>
        </div>
    </div>
</body>
</html>
